---
- name: Install Satellite
  hosts: satellite_server
  vars_files:
    host_vars/satellite_vars.yml
  roles:
    - role: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_options:
          - '--foreman-initial-organization "rodli"'
          - '--foreman-initial-admin-password {{ satellite.satellite_password }}'

    # - role: capsule_certs_generate