---
- name: Configure Red Hat Satellite
  hosts: satellite_server
  vars_files:
    - host_vars/vault.yml
    - host_vars/satellite_vars.yml
  roles:
    # - subscription_manifest

    - role: redhat.satellite.organizations
      vars:
        satellite_server_url: "{{ satellite.satellite_server_url }}"
        satellite_username: "{{ satellite.satellite_username }}"
        satellite_password: "{{ satellite.satellite_password }}"
        satellite_organizations:
          - name: rodli
            label: rodli
            state: present
          - name: operations
            label: operations
            state: present

    - locations

    - repository_set

# Note: I've had the following repository_sync role fail once, and when I ran the playbook again, it succeeded.
# The error message is below.
# msg: 'Task Synchronize synchronize; repository ''Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9.0''; product ''Red Hat Enterprise Linux for x86_64''; organization ''rodli''; ...(6543cf74-caa1-49cf-8ea1-20fc0d3a9c4d) did not succeed. Task information: [''A sub task failed'']'
    - repository_sync

    - role: redhat.satellite.lifecycle_environments
      vars:
        satellite_username: "{{ satellite.satellite_username }}"
        satellite_password: "{{ satellite.satellite_password }}"
        satellite_server_url: "{{ satellite.satellite_server_url }}"
        satellite_organization: "rodli"
        satellite_lifecycle_environments: "{{ satellite.satellite_lifecycle_environments }}"

    - content_views

    - content_view_version

    # - role: redhat.satellite.content_view_publish
    #   vars:
    #     satellite_server_url: "{{ satellite.satellite_server_url }}"
    #     satellite_username: "{{ satellite.satellite_username }}"
    #     satellite_password: "{{ satellite.satellite_password }}"
    #     satellite_organization: "rodli"
    #     satellite_content_views:
    #       - RHEL9_Base_CV

    - role: redhat.satellite.content_view_version_cleanup
      vars:
        satellite_server_url: "{{ satellite.satellite_server_url }}"
        satellite_username: "{{ satellite.satellite_username }}"
        satellite_password: "{{ satellite.satellite_password }}"
        satellite_organization: "rodli"
        satellite_content_view_version_cleanup_keep: "{{ satellite.number_of_content_view_versions_to_keep }}"