---
# tasks file for roles/repository_sync
- name: Sync repository
  redhat.satellite.repository_sync:
    username: "{{ satellite.satellite_username }}"
    password: "{{ satellite.satellite_password }}"
    server_url: "{{ satellite.satellite_server_url }}"
    organization: "rodli"
    product: Red Hat Enterprise Linux for x86_64