---
# tasks file for roles/content_views
- name: "Create or update the RHEL 9 Base content view"
  redhat.satellite.content_view:
    username: "{{ satellite.satellite_username }}"
    password: "{{ satellite.satellite_password }}"
    server_url: "{{ satellite.satellite_server_url }}"
    name: "RHEL9_Base_CV"
    organization: "rodli"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'