---
# tasks file for roles/satellite_pre_install
- name: Open ports for client to Satellite communication.
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
  loop: "{{ satellite.firewall_ports }}"

- name: Register to a Red Hat subscription.
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat.rh_username}}"
    password: "{{ redhat.rh_password }}"
    auto_attach: true

- name: Disable all unecessary repositories, and enable BaseOS, AppStream, Satellite 6.12 for RHEL 8, and Satellite Maintenance 6.12 for RHEL 8.
  community.general.rhsm_repository:
    name: "{{ satellite.enabled_repositories }}"
    purge: true

# The below task warns about a conflict with postgresql:10 and ruby:2.5 as these modules are set to the default module versions on RHEL8. The satellite:el8 has a dependency for modules postgresql:12 and ruby:2.7. These warnings do not cause installation process failure, hence can be ignored safely.
- name: Enable the satellite el8 module.
  ansible.builtin.dnf:
    name: '@satellite:el8'
    state: present
  ignore_errors: true

- name: Update all packages.
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Satellite Server packages.
  ansible.builtin.dnf:
    name: satellite
    state: present

- name: Install chrony package.
  ansible.builtin.dnf:
    name: chrony
    state: present

- name: Start and enable chronyd service.
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Install sos package for opening service requests with Red Hat Technical Support.
  ansible.builtin.dnf:
    name: sos
    state: present
...
# Installing Satellite Server - https://access.redhat.com/documentation/en-us/red_hat_satellite/6.12/html/installing_satellite_server_in_a_connected_network_environment/installing_server_connected_satellite