---
# tasks file for locations
- name: "Create CBR Location"
  redhat.satellite.location:
    username: "{{ satellite.satellite_username }}"
    password: "{{ satellite.satellite_password }}"
    server_url: "{{ satellite.satellite_server_url }}"
    name: "cbr"
    organizations:
      - "rodli"
    state: present