---
# tasks file for roles/repository_set
- name: Enable RHEL 8 RPMs repositories with label
  redhat.satellite.repository_set:
    username: "{{ satellite.satellite_username }}"
    password: "{{ satellite.satellite_password }}"
    server_url: "{{ satellite.satellite_server_url }}"
    organization: "rodli"
    label: "{{ item }}"
    repositories:
      - releasever: "8.0"
  loop:
    - rhel-8-for-x86_64-baseos-rpms
    - rhel-8-for-x86_64-appstream-rpms

- name: Enable RHEL 9 RPMs respositories with label
  redhat.satellite.repository_set:
    username: "{{ satellite.satellite_username }}"
    password: "{{ satellite.satellite_password }}"
    server_url: "{{ satellite.satellite_server_url }}"
    organization: "rodli"
    label: "{{ item }}"
    repositories:
      - releasever: "9.0"
  loop:
    - rhel-9-for-x86_64-baseos-rpms
    - rhel-9-for-x86_64-appstream-rpms
    - satellite-client-6-for-rhel-9-x86_64-rpms