---
satellite:
  number_of_content_view_versions_to_keep: 10
  enabled_repositories:
    - rhel-8-for-x86_64-baseos-rpms
    - rhel-8-for-x86_64-appstream-rpms
    - satellite-6.12-for-rhel-8-x86_64-rpms
    - satellite-maintenance-6.12-for-rhel-8-x86_64-rpms
  firewall_ports:
    - 53/udp
    - 53/tcp
    - 67/udp
    - 69/udp
    - 80/tcp
    - 443/tcp
    - 5647/tcp
    - 8000/tcp
    - 9090/tcp
    - 8140/tcp
  manifest_path: /tmp/manifest.zip
  organization: <ORGANIZATION>
  satellite_hostname_fqdn: "{{ vault_satellite_hostname_fqdn }}"
  satellite_hostname_short: "{{ vault_satellite_hostname_short }}"
  satellite_server_url: "{{ vault_satellite_server_url }}"
  satellite_username: "{{ vault_satellite_username }}"
  satellite_password: "{{ vault_satellite_password }}"
  satellite_organizations:
    - name: rodli
      label: rodli
      state: present
    - name: operations
      label: operations
      state: absent
    - name: finance
      label: finance
      state: absent
  satellite_lifecycle_environments:
    - name: "Dev"
      prior: "Library"
    - name: "Test"
      prior: "Dev"
    - name: "Prod"
      prior: "Test"
  satellite_activation_keys:
    - name: "Basic Activation Key"
      description: "Basic description"
  rhel_products:
    labels:
      - rhel-8-for-x86_64-baseos-rpms
redhat:
  rh_username: "{{ vault_rh_username }}"
  rh_password: "{{ vault_rh_password }}"